"""corregido dependencia transitiva

Revision ID: a1f4982843a3
Revises: c9bbc60ce759
Create Date: 2025-04-18 14:31:47.774113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f4982843a3'
down_revision = 'c9bbc60ce759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DIM_CLIENTE', schema=None) as batch_op:
        batch_op.drop_constraint('DIM_CLIENTE_region_fkey', type_='foreignkey')
        batch_op.drop_column('region')

    with op.batch_alter_table('DIM_TIENDA', schema=None) as batch_op:
        batch_op.drop_constraint('DIM_TIENDA_region_fkey', type_='foreignkey')
        batch_op.drop_column('region')
    op.rename_table('VENDEDOR_TIENDA', 'DIM_VENDEDOR_TIENDA')
    # ### end Alembic commands ###

    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DIM_TIENDA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('DIM_TIENDA_region_fkey', 'DIM_REGION', ['region'], ['region_key'])

    with op.batch_alter_table('DIM_CLIENTE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('DIM_CLIENTE_region_fkey', 'DIM_REGION', ['region'], ['region_key'])
    op.rename_table('VENDEDOR_TIENDA', 'DIM_VENDEDOR_TIENDA')
    # ### end Alembic commands ###
