"""Rename table

Revision ID: ad22f325f17c
Revises: a1f4982843a3
Create Date: 2025-04-18 16:20:00.232542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad22f325f17c'
down_revision = 'a1f4982843a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VENDEDOR_TIENDA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VENDEDOR_TIENDA',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vendedor_key', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tienda_key', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fecha_contratacion', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_renuncia', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.CheckConstraint('fecha_renuncia IS NULL OR fecha_renuncia > fecha_contratacion', name='ck_fecha_renuncia_valida'),
    sa.ForeignKeyConstraint(['tienda_key'], ['DIM_TIENDA.tienda_key'], name='VENDEDOR_TIENDA_tienda_key_fkey1'),
    sa.ForeignKeyConstraint(['vendedor_key'], ['DIM_VENDEDOR.vendedor_key'], name='VENDEDOR_TIENDA_vendedor_key_fkey1'),
    sa.PrimaryKeyConstraint('id', name='VENDEDOR_TIENDA_pkey1')
    )
    # ### end Alembic commands ###
