"""empty message

Revision ID: e3b6e784aa9a
Revises: ad22f325f17c
Create Date: 2025-05-01 22:44:17.977007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b6e784aa9a'
down_revision = 'ad22f325f17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DIM_TIENDA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gerente_key', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'DIM_GERENTE', ['gerente_key'], ['gerente_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DIM_TIENDA', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gerente_key')

    # ### end Alembic commands ###
